// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/discord/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/discord/callback.get').default>>>>
    }
    '/api/auth/discord/login': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/discord/login.get').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/links/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/links/[id].patch').default>>>>
    }
    '/api/links': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/links/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/links/index.post').default>>>>
    }
    '/:code': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/[code]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}